#!/bin/bash
echo "=========================================="
echo "[+] 啟動自動化流量工廠 - 戰情室戰報"
echo "=========================================="
echo "日期時間: $(date '+%Y-%m-%d %H:%M:%S')"
echo "專案路徑: $(pwd)"
echo "累積內容數: $(ls -l contents/ 2>/dev/null | grep ^- | wc -l) 篇"
echo "系統守護狀態: 運行中 (Crontab + Guardian Active)"
echo "金流管道: 中華郵政 (700) 0902544"
echo "遠端同步狀態: $(git remote -v | head -n 1)"
echo "=========================================="
